### ISSUE TITLE
some need to add features

### ISSUE THREAD

**Issue by NetherDragonTw** [Levi2288/Akira-Client#3]
Reach-
add misplace setting
add scaffold(eagle, legit, blatant),(blatant=move and place blocks, eagle=place 2 blocks and shift, and repeat this thing, legit=like speed bridge)
add aimassint
add ESP(PlayerESP, or any but need to add playeresp
playeresp has a setting can select 2d or 3d hitbox and can setting hit box color)
add in menu bottom left previous page button
add in menu bottom right next page button
Hitboxes-
Can see changed hitbox setting (can set color)
That's it! thanks! :D

**Comment by Levi2288** [comment]
Hi!
This is a memory client so most of the things your listed is sadly not possible 😞 
But thanks for the suggestions. 😃

**Comment by NetherDragonTw** [comment]
> Hi! This is a memory client so most of the things your listed is sadly not possible 😞 But thanks for the suggestions. 😃

ok. thanks.
