### ISSUE TITLE
Some modules dont work on lunar client.

### ISSUE THREAD

**Issue by BaitHopper** [Levi2288/Akira-Client#4]
So i tried nametags but then it just left all nametags blank, i dont have the nametags mod on and when i do it on i have the same issue, other than that, great client, i use this on pvp.land, hypixel, and even minemen. I hope this client would get some aim assist though.

**Comment by Levi2288** [comment]
Hi, not all modules are supported on Lunar client.
For example Hitbox and as you mentioned nametags i will try to fix them up tho.
Akira is a memory client so Aim Assist is not possible :c but thanks for the feedback im glad you like my work.
Join our discord server if you want :D https://dsc.gg/akiraclient
