### ISSUE TITLE
[SOLVED] This client is most likely malware. But i have 0 proof xd (Answered it in his reddits post)

### ISSUE THREAD

**Issue by benjathje** [Levi2288/Akira-Client#5]
https://www.reddit.com/r/minecraftclients/comments/z75r03/akira_ghost_client_magic_at_no_cost_more_like/

**Comment by Levi2288** [comment]
I replied to your Reddit post. Please do not claim this things without knowing anything about what you are talking about.

**Comment by emb3rn** [comment]
As someone who hasn't even used the client this is extremely childish. You have no idea what you're talking about and props to the dev for making you look like an absolute tool.
